---
version: 1

kind: experiment

environment:
  resources:
      gpu:
        requests: 1
        limits: 1

build:
  image: vfdev5/mii-dockerfiles:latest
  build_steps: 
  - pip install --no-cache --no-deps --upgrade git+https://github.com/pytorch/ignite.git


declarations:
  data_path: "/data/ssd/cifar10"
  num_epochs: 18
  dropout_p: "None"
  final_weight: 1.2
  batch_size: 512
  weight_decay: 0.1
  width: 4
  depth: 10


run:
  cmd:
    - export PATH=$PATH:/usr/local/nvidia/bin && nvidia-smi
    - export TB_LOGGER_PATH=$POLYAXON_RUN_OUTPUTS_PATH
    - python -u code/main_wrn.py --use_tb_logger --params data_path="{{ data_path }}" \
        model=FasterWideResNet \
        seed=5 num_epochs={{ num_epochs }} \
        batch_size={{ batch_size }} \
        weight_decay={{ weight_decay }} \
        final_weight={{ final_weight }} dropout_p={{ dropout_p }} \
        lr_param_group_0="[(0, 0.0), (6, 0.4), ({{ num_epochs }}, 0.0)]" \
        lr_param_group_1="[(0, 0.0), (6, 0.4), ({{ num_epochs }}, 0.0)]" \
        lr_param_group_2="[(0, 0.0), (6, 0.4), ({{ num_epochs }}, 0.0)]" \
        lr_param_group_3="[(0, 0.0), (6, 0.4), ({{ num_epochs }}, 0.0)]" \
        lr_param_group_4="[(0, 0.0), (6, 0.4), ({{ num_epochs }}, 0.0)]" \
        lr_param_group_5="[(0, 0.0), (6, 0.4), ({{ num_epochs }}, 0.0)]"
